export const countries = [
  { code: "966", country: "Saudi Arabia" },
  { code: "971", country: "United Arab Emirates" },
  { code: "965", country: "Kuwait" },
  { code: "974", country: "Qatar" },
  { code: "973", country: "Bahrain" },
  { code: "968", country: "Oman" },
  { code: "962", country: "Jordan" },
  { code: "961", country: "Lebanon" },
  { code: "20", country: "Egypt" },
  { code: "964", country: "Iraq" },
  { code: "212", country: "Morocco" },
  { code: "213", country: "Algeria" },
  { code: "216", country: "Tunisia" },
  { code: "218", country: "Libya" },
  { code: "249", country: "Sudan" },
  { code: "967", country: "Yemen" },
  { code: "970", country: "Palestine" },
  { code: "963", country: "Syria" },
  { code: "222", country: "Mauritania" },
  { code: "252", country: "Somalia" },
  { code: "269", country: "Comoros" },
  { code: "253", country: "Djibouti" },
];
